library("dplyr")
setwd("~/OneDrive/Horizan/LocalFiles/RawData")
all_google_ratings <- read.csv(file = "predicted_google_rating_avgs.csv", stringsAsFactors = FALSE)
safety_ratings <- read.csv(file = 'SafetyData.csv', stringsAsFactors = FALSE)
internet_ratings <- read.csv(file = 'InternetData.csv', stringsAsFactors = FALSE)
facility_ratings <- data.frame('Schools' = internet_ratings$school, 'Facility' = internet_ratings$pred_Facilities)
social_ratings <- data.frame('Schools' = all_google_ratings$school, 'Social' = all_google_ratings$pred_Social)
club_ratings <- data.frame('Schools' = all_google_ratings$school, 'Club' = all_google_ratings$pred_Clubs)
oppo_ratings <- data.frame('Schools' = all_google_ratings$school, 'Opportunities' = all_google_ratings$pred_Opportunities)
internet_ratings <- data.frame('Schools' = internet_ratings$school, 'Internet' = internet_ratings$average.internet.rating..adjusted.)
social_stats <- quantile(social_ratings$Social)
oppo_stats <- quantile(oppo_ratings$Opportunities)
internet_stats <- quantile(internet_ratings$Internet)
safety_stats <- quantile(safety_ratings$Safety)
club_stats <- quantile(club_ratings$Club)
hist(facility_ratings$Facility, breaks = 3)
hist(club_ratings$Club, breaks = 5)
hist(safety_ratings$Safety, breaks = 5)
hist(oppo_ratings$Opportunities, breaks = 5)
hist(internet_ratings$Internet, breaks = 5)
hist(social_ratings$Social, breaks = 5)
